import { IconsType } from "projects/rating-swiper/src/public-api";

export const icons = {
    "logo": "assets/images/light/logo.svg",
    "actions": {
        "back": "assets/svg/back_icon.svg"
    },
    "splash": {
        "logo": "assets/images/light/splash-logo.svg",
        "step1": "assets/images/step-1.png",
        "step2": "assets/images/step-2.png",
        "step3": "assets/images/step-3.png",
        "vector1": "assets/images/vector-1.png",
        "vector2": "assets/images/vector-2.png",
        "vector3": "assets/images/vector-3.png"
    },
    "chat": "assets/icons/light/chat.svg",
    "place": "assets/icons/light/place.svg",
    "temple": "assets/icons/light/temple.svg",
    "pulse": "assets/icons/light/pulse.svg",
    "geo": "assets/icons/light/geo.svg",
    "messaging": "assets/icons/light/messaging.svg",
    "mic": "assets/icons/light/mic.svg",
    "profile": "assets/icons/light/profile.svg",
    "itineraryProfile": "assets/icons/light/itineraryProfile.svg",
    "theme": "assets/icons/light/theme.svg",
    "star": "assets/icons/light/star.svg",
    "hash": "assets/icons/light/hash.svg",
    "send": "assets/icons/light/send.svg",
    "location": "assets/icons/light/location.svg",
    "support": "assets/icons/light/support.svg",
    "add": "assets/icons/light/add.svg",
    "close": "assets/icons/light/close.svg",
    "yellowReviewStar": "assets/icons/yellow-review-star.svg",
    "dragIcon": "assets/icons/drag_icon.svg",
    "addMapsLocation": "assets/icons/maps-add-icon.svg",
    "eye": "assets/icons/light/eye.svg",
    "eye2": "assets/icons/light/eye-2.svg",
    "branch": "assets/icons/light/branch.svg",
    "comment": "assets/icons/light/comment.svg",
    "home": "assets/icons/light/home.svg",
    "coffee": "assets/icons/light/coffee.svg",
    "castle": "assets/icons/light/castle.svg",
    "map": "assets/icons/light/itinerary-map.svg",
    "writingPen": "assets/icons/light/writing-pen.svg",
    "noVision": "assets/icons/light/no-vision.svg",
    "filter": "assets/icons/light/filter.svg",
    "menu": "assets/icons/light/menu.svg",
    "createItinerary": "assets/icons/light/create-itinerary.svg",
    "luckyStar": "assets/icons/light/lucky-star.svg",
    "quickItinerary": "assets/icons/light/quick-itinerary.svg",
    "loveOutline": "assets/icons/light/love-outline.svg",
    "helpHexagon": "assets/icons/light/help-hexagon.svg",
    "share": "assets/icons/light/share.svg",
    "archive": "assets/icons/light/archive.svg",
    "pinkArchive": "assets/icons/light/archivepink.svg",
    "pinkLove": "assets/icons/light/pink-love.svg",
    "chevronBack": "assets/icons/light/chevron-back.svg",
    "footer": {
        "home": "assets/icons/footer/light/home.svg",
        "clients": "assets/icons/footer/light/clients.svg",
        "add": "assets/icons/footer/add.svg",
        "statistics": "assets/icons/footer/light/statistics.svg",
        "account": "assets/icons/footer/light/account.svg",
        "selected": {
            "home": "assets/icons/footer/selected-home.svg",
            "clients": "assets/icons/footer/selected-clients.svg",
            "statistics": "assets/icons/footer/selected-statistics.svg",
            "account": "assets/icons/footer/selected-account.svg"
        },
        "guruFooter": {
            "settings": "assets/icons/footer/light/settings.svg",
            "settingsActive": "assets/icons/footer/settingsActive.svg",
            "home": "assets/icons/footer/guru-footer/light/home.svg",
            "homeActive": "assets/icons/footer/guru-footer/active/home.svg",
            "heart": "assets/icons/footer/guru-footer/light/heart.svg",
            "heartActive": "assets/icons/footer/guru-footer/active/heart.svg",
            "chat": "assets/icons/footer/guru-footer/light/chat.svg",
            "chatActive": "assets/icons/footer/guru-footer/active/chat.svg",
            "insights": "assets/icons/footer/guru-footer/insights.svg",
            "insightsActive": "assets/icons/footer/guru-footer/active/insights.svg",
            "itineraries": "assets/icons/footer/guru-footer/light/Itineraries.svg",
            "itinerariesActive": "assets/icons/footer/guru-footer/active/Itineraries.svg",
            "profile": "assets/icons/footer/guru-footer/light/profile.svg",
            "profileActive": "assets/icons/footer/guru-footer/active/profile.svg",
            "constituents": "assets/icons/footer/guru-footer/light/constituents.svg",
            "constituentsActive": "assets/icons/footer/guru-footer/active/constituents.svg",
            "statsActive": "assets/icons/footer/guru-footer/active/stats.svg",
            "stats": "assets/icons/footer/guru-footer/light/stats.svg",
            "messenger": "assets/icons/footer/guru-footer/light/messenger.svg",
            "messengerActive": "assets/icons/footer/guru-footer/active/messenger.svg"
        }
    },
    "header": {
        "back": "assets/icons/header/light/back.svg",
        "back2": "assets/svg/back2.svg",
        "notification": "assets/icons/header/light/notification.svg",
        "menu": "assets/icons/header/menu.svg",
        "notificationAlert": "assets/icons/header/notification-alert.svg",
        "dateIcon": "assets/icons/date.svg",
        "coin": "assets/icons/coin.svg"
    },
    "messageTakeoverFab": {
        "context": "assets/icons/message-takeover-fab/dark/context.svg",
        "live": "assets/icons/message-takeover-fab/dark/live.svg",
        "scan": "assets/icons/message-takeover-fab/dark/scan.svg",
        "translate": "assets/icons/message-takeover-fab/dark/translate.svg",
        "vent": "assets/icons/message-takeover-fab/dark/vent.svg",
        "close": "assets/icons/message-takeover-fab/dark/fab-close.svg"
    },
    "unmatched": {
        "hash": "assets/icons/light/hash.svg",
        "star": "assets/icons/light/star.svg",
        "edit": "assets/icons/light/edit.svg"
    },
    "paymentCard": {
        "mastercard": "assets/icons/light/card-brands/mastercard.svg",
        "visa": "assets/icons/light/card-brands/visa.svg",
        "americanExpress": "assets/icons/light/card-brands/american-express.svg",
        "bank": "assets/icons/light/card-brands/bank.svg"
    },
    "password": {
        "lock": "assets/icons/light/password/lock.svg",
        "unlock": "assets/icons/light/password/unlock.svg",
        "mail": "assets/icons/light/password/mail.svg"
    },
    "accountSetup": {
        "googleCalender": "assets/icons/social/google-calendar.svg",
        "microsoft": "assets/icons/social/microsoft.svg"
    },
    "common": {
        "arrowDownRed": "assets/icons/dark/common/arrow-down-red.svg",
        "arrowRightRed": "assets/icons/dark/common/arrow-right-red.svg",
        "arrowRight": "assets/icons/light/common/arrow-right.svg",
        "dates": "assets/icons/light/common/dates.svg",
        "earnings": "assets/icons/light/common/earnings.svg",
        "notification": "assets/icons/light/common/notification.svg",
        "arrowDown": "assets/icons/arrow_down.svg",
        "verified": "assets/icons/common/verified.svg",
        "trash": "assets/icons/light/common/trash.svg",
        "warning": "assets/icons/light/common/warning.svg",
        "search": "assets/icons/light/common/search.svg",
        "email": "assets/icons/light/common/email.svg",
        "mobile": "assets/icons/light/common/mobile.svg",
        "dob": "assets/icons/light/common/dob.svg",
        "education": "assets/icons/light/common/education.svg",
        "gender": "assets/icons/light/common/gender.svg",
        "height": "assets/icons/light/common/height.svg",
        "language": "assets/icons/light/common/language.svg",
        "location": "assets/icons/light/common/location.svg",
        "locked": "assets/icons/light/common/locked.svg",
        "name": "assets/icons/light/common/name.svg",
        "username": "assets/icons/light/common/username.svg",
        "lookingFor": "assets/icons/light/common/lookingFor.svg",
        "religion": "assets/icons/light/common/religion.svg",
        "work": "assets/icons/light/common/work.svg",
        "logout": "assets/icons/light/common/logout.svg",
        "plus": "assets/icons/light/common/plus.svg",
        "plusOff": "assets/icons/light/common/plus-off.svg",
        "minus": "assets/icons/light/common/minus.svg",
        "minusOff": "assets/icons/light/common/minus-off.svg",
        "listArrow": "assets/icons/light/common/list-arrow.svg",
        "lock": "assets/icons/light/common/lock.svg",
        "defualtUserIcon": "assets/icons/light/common/defualt-user-icon.svg",
        "dotMenu": "assets/icons/light/dot-menu.svg"
    },
    "client": {
        "drinking": "assets/icons/light/client/drinking.svg",
        "exercise": "assets/icons/light/client/exercise.svg",
        "homeTown": "assets/icons/light/client/homeTown.svg",
        "Interests": "assets/icons/light/client/Interests.svg",
        "kids": "assets/icons/light/client/kids.svg",
        "political": "assets/icons/light/client/political.svg",
        "pronoun": "assets/icons/light/client/pronoun.svg",
        "smoking": "assets/icons/light/client/smoking.svg",
        "zodiac": "assets/icons/light/client/zodiac.svg",
        "edit": "assets/icons/light/client/edit.svg"
    },
    "separator": "assets/icons/light/separator.svg",
    "calendar": "assets/icons/light/calendar.svg",
    "locationSolid": "assets/icons/light/location-solid.svg",
    "time": "assets/icons/light/time.svg",
    "profession": "assets/icons/unmatched-registration/profession.svg",
    "love": "assets/icons/unmatched-registration/love.svg",
    "info": "assets/icons/unmatched-registration/info.svg",
    "guru": {
        "accountType": "assets/icons/light/guru/account_type.svg",
        "dates": "assets/icons/light/guru/dates.svg",
        "money": "assets/icons/light/guru/money.svg",
        "rentNumber": "assets/icons/light/guru/rente_number.svg",
        "lock": "assets/icons/light/guru/lock.svg"
    },
    "userRegistrationPreview": {
        "signup": "assets/images/user-registration-preview/signup.jpg",
        "verify": "assets/images/user-registration-preview/verify.jpg",
        "location": "assets/images/user-registration-preview/location-permission.jpg",
        "maps": "assets/images/user-registration-preview/maps.jpg",
        "accountDetails": "assets/images/user-registration-preview/account-details.jpg",
        "birthday": "assets/images/user-registration-preview/my-birthday.jpg",
        "interests": "assets/images/user-registration-preview/my-interests.jpg",
        "gender": "assets/images/user-registration-preview/select-gender.jpg",
        "interestedGender": "assets/images/user-registration-preview/interested-in.jpg",
        "photos": "assets/images/user-registration-preview/add-photos.jpg",
        "datingPreferences": "assets/images/user-registration-preview/date-preferences.jpg",
        "goalsInterests": "assets/images/user-registration-preview/goals-and-interests.jpg",
        "ageHeightWeight": "assets/images/user-registration-preview/age-height-weight.jpg",
        "faceEthnicity": "assets/images/user-registration-preview/face-and-ethnicity.jpg",
        "bustHip": "assets/images/user-registration-preview/bust-waist-and-hip.jpg",
        "swipe": "assets/images/user-registration-preview/implicit-swipe.jpg",
        "congratulations": "assets/images/user-registration-preview/congratulations.jpg",
        "summary": "assets/images/user-registration-preview/summary-section.jpg",
        "preferenceVsSwipes": "assets/images/user-registration-preview/preferences-vs-swipe.jpg",
        "accountSetup": "assets/images/user-registration-preview/account-setup.jpg",
        "accounts": "assets/images/user-registration-preview/calendar-accounts.jpg",
        "calendar": "assets/images/user-registration-preview/calendar.jpg",
        "accountTakeOver": "assets/images/user-registration-preview/account-takeover.jpg",
        "setupDatingAccount": "assets/images/user-registration-preview/setup-dating-accounts.jpg",
        "newAccounts": "assets/images/user-registration-preview/new-accounts.jpg",
        "billing": "assets/images/user-registration-preview/complete.jpg",
        "payment": "assets/images/user-registration-preview/payment.jpg",
        "electivePayment": "assets/images/user-registration-preview/elective-payment.jpg",
        "paymentMethod": "assets/images/user-registration-preview/payment-method.jpg",
        "paymentSuccess": "assets/images/user-registration-preview/payment-success.jpg",
        "referralCode": "assets/images/user-registration-preview/referral-code.jpg",
        "username": "assets/images/user-registration-preview/matcher-username.jpg",
        "matcherPhone": "assets/images/user-registration-preview/matcher-phonenumber.jpg",
        "matcherRegister": "assets/images/user-registration-preview/matcher-register.jpg",
        "matcherReferralCode": "assets/images/user-registration-preview/matcher-referral-code.jpg",
        "matcherUsername": "assets/images/user-registration-preview/matcher-username.jpg",
        "matcherDocument": "assets/images/user-registration-preview/matcher-document.jpg",
        "matcherVerify": "assets/images/user-registration-preview/matcher-verify.jpg"
    },
    "socialIcons": {
        "google": "assets/icons/social/google.svg",
        "facebook": "assets/icons/social/facebook.svg",
        "twitter": "assets/icons/social/twitter.svg"
    },
    "heart": "assets/icons/implicit-swipes/heart.svg",
    "dislike": "assets/icons/implicit-swipes/dislike.svg",
    "superLike": "assets/icons/implicit-swipes/superlike.svg",
    "dashboard": {
        "contentCard": {
            "lockRightIcon": "assets/icons/unmatched/dashboard/lock-right-chevron.svg"
        },
        "insights": {
            "grid": "assets/icons/grid/grid.svg",
            "content": "assets/icons/content.svg",
            "separator": "assets/icons/separator.svg",
            "searchTool": "assets/icons/search-tool.svg",
            "placeholder": "assets/icons/placeholder.svg"
        }
    },
    "toggleIcons": {
        "left": {
            "enable": "assets/icons/mail.svg",
            "disable": "assets/icons/disable-mail.svg"
        },
        "right": {
            "enable": "assets/icons/phone.svg",
            "disable": "assets/icons/disable-phone.svg"
        },
        "thumb": "assets/icons/dark-thumb.svg"
    },
    "telInputIcons": {
        "countrySelectorImage": "assets/icons/tel-input/concave-phone-num-bg.svg"
    }
}